apiVersion: main
kind: 
metadata:
  name: backend
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
  labels:
    app: flask
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  # The selector tells the service on which deployment it should be applied
  selector:
    app: flask
    tier: backend