services:
  - type: web
    name: gamerock-welfare
    runtime: python
    plan: free
    env: python
    build:
      commands:
        - pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: SECRET_KEY
        value: "lpsrgrgnrtowp5tn_tret-region"
      - key: DATABASE_URL
        fromDatabase:
          name: gamerock-db
          property: connectionString
databases:
  - name: gamerock-db
    region: oregon
    plan: free
