"""empty message

Revision ID: 224df89f2a24
Revises: 
Create Date: 2026-08-02 20:45:37.714669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224df89f2a24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    from app import create_app, db
    app = create_app()
    with app.app_context():
        insp = inspect(db.engine)
        cols = [c['name'] for c in insp.get_columns('community_event')]
        if 'image' not in cols:
            with op.batch_alter_table('community_event', schema=None) as batch_op:
                batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_event', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
