"""Change user.phone_num from Integer to String

Revision ID: 761f6dbb1a6a
Revises: 37a244a688de
Create Date: 2026-08-17 08:37:45.304922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761f6dbb1a6a'
down_revision = '37a244a688de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone_num',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone_num',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
