"""Add email column to member table

Revision ID: 8021245e48fb
Revises: 39dd015614a4
Create Date: 2026-08-03 07:38:29.881106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8021245e48fb'
down_revision = '39dd015614a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    from app import create_app, db
    app = create_app()
    with app.app_context():
        insp = inspect(db.engine)
        cols = [c['name'] for c in insp.get_columns('member')]
        if 'email' not in cols:
            with op.batch_alter_table('member', schema=None) as batch_op:
                batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
