"""rename wife to spouse

Revision ID: e5d40eef8a5e
Revises: 8021245e48fb
Create Date: 2026-08-16 00:30:58.977465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5d40eef8a5e'
down_revision = '8021245e48fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('wife', 'spouse')
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.alter_column('wife_id', new_column_name='spouse_id')
        batch_op.drop_constraint(batch_op.f('child_wife_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'spouse', ['spouse_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('child_wife_id_fkey'), 'wife', ['spouse_id'], ['id'])
        batch_op.alter_column('spouse_id', new_column_name='wife_id')

    op.rename_table('spouse', 'wife')
    # ### end Alembic commands ###
